language: ruby
rvm:
  - 2.5.0

services:
  - postgresql

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
- gem update --system
- gem install bundler


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - psql -c 'create database pgapp_test;' -U postgres

branches:
  only:
  - master
