language: ruby
rvm:
  - 2.5.0

services:
  - postgresql

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3
- gem update --system
- gem install bundler

install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
- tar -xzf geckodriver-v0.20.0-linux64.tar.gz -C bin
- export PATH=$(pwd)/bin:$PATH

before_script:
  - psql -c 'create database pgapp_test;' -U postgres

branches:
  only:
  - master
